### ISSUE TITLE
wordsGerman missing

### ISSUE THREAD

**Issue by Tobsucht** [danielnaber/jwordsplitter#10]
The current maven-snapshot doesn't contain the file "wordsGerman.ser". I think this is just a build problem? Could you fix this?

**Comment by danielnaber** [comment]
When I build with `mvn clean package` I get `jwordsplitter-4.2-SNAPSHOT.jar` and that contains `de/danielnaber/jwordsplitter/wordsGerman.ser`.

**Comment by Tobsucht** [comment]
And when you import it into a project using:
`<dependency>
            <groupId>de.danielnaber</groupId>
            <artifactId>jwordsplitter</artifactId>
            <version>4.2-SNAPSHOT</version>
        </dependency>`
?

**Comment by danielnaber** [comment]
Works for me, too. Of course, you have to use `mvn install` instead of `mvn package` then.

**Comment by Tobsucht** [comment]
Weird, now its working. Did the same before, sorry for the false posititve.
