### ISSUE TITLE
GermanWordSplitter NPE when accessing disambiguator

### ISSUE THREAD

**Issue by simasch** [danielnaber/jwordsplitter#13]
disambiguator is null when using the new constructor.

**Comment by danielnaber** [comment]
Should be fixed, I actually forgot to call `init()`, which was probably also the cause for #12.

**Comment by simasch** [comment]
But init() will call getWordList() and will load the EmbeddedGermanDictonary.

    protected Set<String> getWordList() {
        return EmbeddedGermanDictionary.getWords();
    }

Is this correct?

**Comment by danielnaber** [comment]
Using the embedded dictionary for `GermanInterfixDisambiguator` seems correct - that's not the main dictionary, but rather a (very simple) attempt to remove ambiguities.

**Comment by simasch** [comment]
Ok. Got you
Thanks.
