### ISSUE TITLE
missing directory(?)

### ISSUE THREAD

**Issue by Tedwinder** [danielnaber/jwordsplitter#16]
Hi, when I tried to run the build script I encountered the error: cannot access src/main/resources/de/danielnaber/jwordsplitter/wordsGerman.ser: no such file or directory.  I navigated to the folder on GitHub, and sure enough there's no wordsGerman.ser. . . .

**Comment by danielnaber** [comment]
This probably means there was an error earlier in the build script. Could you paste its complete output?

**Comment by Tedwinder** [comment]
I did a screen capture of the output I got. I'm trying to run it on a linux
server. . . . I think if I run it on my linux machine at home the 'mvn:
command not found' should go away, so I'm not really worried about that.

Thanks so much for getting back to me.  I think your program will be very
useful for some NLP research I'm doing!

Ted Callow

**Comment by Tedwinder** [comment]
I'm not sure if you were able to get the attachment from the previous, so
hopefully it comes through to one of these recipients. Ted

**Comment by danielnaber** [comment]
You cannot attach here I think. But yes, you need Maven (`mvn`), otherwise you cannot build the code (and the `.ser` file).

**Comment by Tedwinder** [comment]
I see. Thank you for the clarification.
