### ISSUE TITLE
GermanInterfixDisambiguator

### ISSUE THREAD

**Issue by r-hempenstall** [danielnaber/jwordsplitter#25]
I was trying to extend `AbstractWordSplitter` as was suggested in the README to see how the library would work with Swedish but one of the abstract methods returns an instance of `GermanInterfixDisambiguator` which is package-private so I can't extend the `AbstractWordSplitter`. It also wouldn't make much sense for a class dealing with Swedish words to need a method which returns a German specific class.

**Comment by danielnaber** [comment]
I've made the class public now. PRs with a cleaner solution are welcome.

**Comment by r-hempenstall** [comment]
Thank you. I haven't looked in detail enough to know whether or not that was a problem. I'm just evaluating libraries at the moment. Will create a PR if I get chance. Thanks!
